cache = true
max_cache_age = "1d"
max_retries = 3
retry_wait_time = 2
timeout = 30
accept = [200, 206, 429]
exclude_loopback = true
exclude = [
  '^https://leetcode[.]com/$',
  '^https://academy[.]postman[.]com/$',
  '^https://exercism[.]org/',
  '^https://coolors[.]co/$',
  '^https://www[.]open[.]edu/openlearn/languages$',
  '^https://www[.]cursoemvideo[.]com/curso/curso-de-algoritmo/$',
  '^https://dictionary[.]cambridge[.]org/$',
]
