import { useState } from 'react';
import { demoCases, simulateDemo } from './data/agent-simulation';
export default function AgentPlayground(){
 const [selected,setSelected]=useState(0),[position,setPosition]=useState(0);
 const c=demoCases[selected],r=simulateDemo(c);
 const scenes=[
  {name:'APP',title:'O pedido entra no aplicativo',code:c.request,why:'O texto pede um alvo. A identidade vem de um contexto autenticado separado. Aqui usuario-A e as permissões são fixtures; não existe login real.'},
  {name:'ROUTER',title:'Escolher a rota antes da tool',code:`rota = ${r.route}`,why:r.route==='ambiguous'?'Há duas intenções sem prioridade; pedir esclarecimento evita escolher por palpite.':r.route==='out_of_scope'?'Não há capacidade aprovada para este pedido. O fluxo para sem consultar dados.':'O comando exato /perfil ou /agenda tem prioridade. A palavra agenda no restante não pode trocar essa rota. Esta política é uma escolha do projeto, não do protocolo MCP.'},
  {name:'AGENT',title:'Preparar uma chamada, sem executar por conta própria',code:(r.route==='perfil'||r.route==='agenda')?JSON.stringify({name:r.route==='agenda'?'consultar_agenda':'consultar_perfil',arguments:{clienteId:c.clientId}},null,2):'Nenhuma chamada: esclarecer ou explicar o limite.',why:'No sistema real, o modelo pode propor a tool; o host executa a chamada e administra o ciclo. Esta tela mostra decisões pré-definidas, sem um modelo.'},
  {name:'TOOL',title:'Validar antes de consultar',code:!r.valid?'Schema inválido → parar':!c.allowed?'Permissão negada → parar antes da busca':r.lookup?'Entrada válida + permissão de fixture → ler a fonte fictícia selecionada':'Fluxo interrompido → nenhuma leitura',why:'O adaptador e o servidor aplicam validação e autorização. Uma instrução no prompt ou uma anotação read-only não substitui esses controles.'},
  {name:'RESULTADO',title:'Preservar dados, ausências e falhas',code:JSON.stringify(r.result,null,2),why:'Este é o envelope de negócio fictício. Não é o envelope JSON-RPC/MCP: ao integrar, mapeie falhas de protocolo, erros da tool e estados de negócio separadamente.'},
  {name:'RESPOSTA',title:'Responder somente com o que foi sustentado',code:r.response,why:`Leituras autorizadas: ${r.lookup?1:0}. Tools chamadas: ${r.calls.join(', ')||'nenhuma'}. Escritas/envios: 0. No caso de injection, essa regra é fixa na simulação; teste o comportamento do modelo real no ambiente antes de confiar nele.`}
 ];
 const scene=scenes[position];
 return <section className="agent-demo" aria-label="Simulação didática do fluxo"><span className="eyebrow">VEJA AS PEÇAS EM AÇÃO</span><h3>Uma pergunta, por dentro do assistente</h3><p>Simulação didática, sem IA, API ou conexão MCP. Não precisa instalar nada. Avance e explique por que cada camada existe.</p><label htmlFor="demo-case">Escolha o que acontece</label><select id="demo-case" value={selected} onChange={e=>{setSelected(Number(e.target.value));setPosition(0);}}>{demoCases.map((item,i)=><option key={item.id} value={i}>{item.label}</option>)}</select><div className="agent-demo-track" aria-label="Camadas">{scenes.map((s,i)=><span key={s.name} className={i===position?'active':''} aria-current={i===position?'step':undefined}>{s.name}</span>)}</div><div className="agent-demo-scene" aria-live="polite"><strong>{position+1}/6 · {scene.title}</strong><pre tabIndex={0}><code>{scene.code}</code></pre><p>{scene.why}</p></div><div className="agent-demo-controls"><button onClick={()=>setPosition(p=>p-1)} disabled={position===0}>Voltar uma camada</button><button onClick={()=>setPosition(p=>p===5?0:p+1)}>{position===5?'Recomeçar o caso':'Ver próxima camada'}</button></div><details><summary>Depois de observar, tente explicar</summary><p>Na colisão, por que agenda não vence /perfil? No acesso negado, houve busca? No campo ausente, a resposta poderia completar a biografia? Compare os casos e volte ao ponto onde sua explicação ainda não ficou clara.</p></details></section>;
}
